"""
Unified theme — clean modern palette, single font stack.
"""
import customtkinter as ctk

# ===== Backgrounds =====
COLOR_BG = "#F5F6F8"
COLOR_CARD = "#FFFFFF"
COLOR_CARD_ALT = "#F8F9FB"
COLOR_RUNNING_BG = "#0F172A"

# ===== Text =====
COLOR_TEXT = "#1E293B"
COLOR_TEXT_SECONDARY = "#64748B"
COLOR_TEXT_MUTED = "#94A3B8"

# ===== Accent =====
COLOR_BLUE = "#3B82F6"
COLOR_BLUE_HOVER = "#2563EB"
COLOR_RED = "#EF4444"
COLOR_RED_HOVER = "#DC2626"
COLOR_GREEN = "#22C55E"
COLOR_CYAN = "#06B6D4"
COLOR_PURPLE = "#8B5CF6"
COLOR_ORANGE = "#F59E0B"

# ===== Borders =====
COLOR_BORDER = "#E2E8F0"

# ===== Sidebar (dark) =====
COLOR_SIDEBAR_BG = "#111827"
COLOR_SIDEBAR_NAV = "#9CA3AF"
COLOR_SIDEBAR_NAV_HOVER = "#1F2937"
COLOR_SIDEBAR_NAV_ACTIVE = "#1E3A5F"
COLOR_SIDEBAR_ACCENT = "#60A5FA"

# ===== Compact window =====
COLOR_TRANSPARENT_KEY = "#000001"
COLOR_COMPACT_BG = "#1E293B"

# ===== Fonts (single consistent stack) =====
FONT_TITLE = ("Microsoft YaHei UI", 24, "bold")
FONT_HEADING = ("Microsoft YaHei UI", 16, "bold")
FONT_BODY = ("Microsoft YaHei UI", 13)
FONT_SMALL = ("Microsoft YaHei UI", 11)
FONT_TIMER = ("Consolas", 72, "bold")
FONT_NANO_TIMER = ("Consolas", 18, "bold")

# Legacy aliases for minimal diff
COLOR_APPLE_BG = COLOR_BG
COLOR_CARD_WHITE = COLOR_CARD
COLOR_CARD_ALT = COLOR_CARD_ALT
COLOR_TEXT_PRIMARY = COLOR_TEXT
COLOR_TEXT_MUTED = COLOR_TEXT_MUTED
COLOR_ACCENT_BLUE = COLOR_BLUE
COLOR_ACCENT_RED = COLOR_RED
COLOR_ACCENT_GREEN = COLOR_GREEN
COLOR_ACCENT_CYAN = COLOR_CYAN
COLOR_SEPARATOR = COLOR_BORDER
COLOR_BORDER_SOFT = COLOR_BORDER
COLOR_BUTTON_NEUTRAL = "#F1F5F9"
COLOR_BUTTON_NEUTRAL_HOVER = "#E2E8F0"
COLOR_SUCCESS_BG = "#ECFDF5"
COLOR_DANGER_BG = "#FEF2F2"
COLOR_WARNING_BG = "#FFFBEB"
COLOR_SIDEBAR_CARD = "#1F2937"
COLOR_SIDEBAR_NAV_TEXT = COLOR_SIDEBAR_NAV
COLOR_SIDEBAR_NAV_HOVER = COLOR_SIDEBAR_NAV_HOVER
COLOR_SIDEBAR_NAV_ACTIVE = COLOR_SIDEBAR_NAV_ACTIVE
COLOR_RUNNING_CARD = "#1E293B"
COLOR_ACCENT_PURPLE = COLOR_PURPLE
COLOR_ACCENT_ORANGE = COLOR_ORANGE
COLOR_GLASS_BG = COLOR_BG
COLOR_PANEL_SOFT = "#F0F2F5"
FONT_NORMAL = ("Microsoft YaHei UI", 13)
FONT_TIMER_LABEL = ("Microsoft YaHei UI", 13)
FONT_NANO_USER = ("Microsoft YaHei UI", 11, "bold")
FONT_CN_TITLE = FONT_TITLE
FONT_CN_HEADING = FONT_HEADING
FONT_CN_BODY = FONT_BODY
FONT_CN_SMALL = FONT_SMALL
FONT_BOLD = FONT_HEADING
